
//
//  R.swift
//  Project : DrawerDemo
//
//  Auto generated by ReflectCode.com 
//
//  R.swift file to hold the details of resources used in the project
//  Used for compatibility with swift code generated from Android code
//
import Foundation
import UIKit
 
extension UIView {
    func subviewsRecursive() -> [UIView] {
        return subviews + subviews.flatMap { $0.subviewsRecursive() }
    }
}
 
    //*** Struct for all resources used in project
    struct R {
 
    //*** Struct for tag assigned to UI resources
        struct id {
            static let drawer_layout = 1000
            static let content_frame = 1001
            static let toolbar = 1002
            static let textView = 1003
            static let RC_ID_1004 = 1004
            static let tvEventLog = 1005
            static let tvLog = 1006
            static let nav_view = 1007
            static let RC_ID_1008 = 1008
            static let RC_ID_1009 = 1009
            static let drawerImage = 1010
            static let drawerBtn = 1011
            static let RC_ID_1012 = 1012
            static let RC_ID_1013 = 1013
            static let RC_ID_1014 = 1014
            static let nav_camera = 1015
            static let nav_gallery = 1016
            static let nav_slideshow = 1017
            static let nav_manage = 1018
            static let RC_ID_1019 = 1019
            static let textView2 = 1020
            static let RC_ID_1021 = 1021
            static let RC_ID_1022 = 1022
            static let RC_ID_1023 = 1023
            static let RC_ID_1024 = 1024
            static let RC_ID_1025 = 1025
        }
 
 
    //*** Struct for tag assigned to Layout files (xib and storyboard)
        struct layout {
            static let activity_drawer                = 0
            static let camera_activity                = 1
            static let nav_header                     = 2
        }
 
        public static let layoutResources :[String] = ["activity_drawer", "camera_activity", "nav_header", ]
 
 
    //*** Structure for String resources IDs
        struct string {
            static let app_name                       = 100000
            static let importPic                      = 100001
            static let gallery                        = 100002
            static let slideshow                      = 100003
            static let tools                          = 100004
        }

        public static let stringResources :[String] = [  "string_app_name", "string_importPic", "string_gallery", "string_slideshow", 
                          "string_tools" ] 
 
 
    //*** Struct for Array resources of various types
        struct array {
        }

        public static let arrayResources :[String] = [ ] 
 
 
    //*** Struct for Dimention resources
        struct dimen {
        }

        public static let dimenResources :[String] = [ ] 
 
 
    //*** Structure for Boolean resources
        struct bool {
        }

        public static let boolResources :[String] = [ ] 
 
 
    //*** Struct for Color values defined in project
        struct color {
            static let colorPrimary                   = 500000
            static let colorPrimaryDark               = 500001
            static let colorAccent                    = 500002
            static let colorBlack                     = 500003
            static let colorGray                      = 500004
            static let colorWhite                     = 500005
        }

        public static let colorResources :[String] = [  "colorPrimary", "colorPrimaryDark", "colorAccent", "colorBlack", 
                          "colorGray", "colorWhite" ] 
 
 
    //*** structure for Integer type of resources
        struct integer {
        }

        public static let integerResources :[String] = [ ] 
 
 
    //*** Structure of IDs for all Drawable resources
        struct drawable {
            static let rc_logo                        = 800000
            static let rc_logo_round                  = 800001
            static let burger_menu_24                 = 800002
            static let camera                         = 800003
            static let gallery                        = 800004
            static let manage                         = 800005
            static let slideshow                      = 800006
        }

        public static let drawableFileName :[String] = [  "rc_logo" , "rc_logo_round" , "burger_menu_24" , "camera" , "gallery" , 
                          "manage" , "slideshow"  ] 
 
    }
 
// --[ End of R.swift ]-- 

